site_name: Aiuta Docs
site_url: https://docs.aiuta.com/
site_author: Aiuta USA, Inc
site_description: >-
  Aiuta Virtual Try-On Solutions

copyright: Copyright &copy; 2024 - 2025 Aiuta USA, Inc

nav:
  - About: index.md
    
  - SDK:
    - sdk/index.md
    - Demo Apps: sdk/demo-apps.md
    - Pages:
      - Welcome: sdk/about/pages/welcome-screen.md
      - Onboarding: sdk/about/pages/onboarding.md
      - Consent: sdk/about/pages/consent.md
      - Image Picker: sdk/about/pages/image-picker.md
      - Loading: sdk/about/pages/loading-screen.md
      - Results: sdk/about/pages/results-screen.md
    - Diagrams:
      - Data Flow: sdk/about/diagrams/data-flow.md
      - Authentication: sdk/about/diagrams/authentication.md
      - Full Interaction: sdk/about/diagrams/interaction-sequence.md
    - Resources:
      - Icons: sdk/about/resources/icons.md
      - Images: sdk/about/resources/images.md
      - Colors: sdk/about/resources/colors.md
      - Shapes: sdk/about/resources/shapes.md
      - Typography: sdk/about/resources/typography.md
      - Localization: sdk/about/resources/localization.md
      - Other: sdk/about/resources/other.md
    - Analytics: 
      - Events: sdk/about/analytics/analytics.md
      - Errors: sdk/about/analytics/errors.md

  - Developer:
    - sdk/developer/index.md
    - Product: sdk/developer/product.md
    - Configuration:
      - sdk/developer/configuration/index.md
      - Auth: sdk/developer/configuration/auth.md
      - Analytics: sdk/developer/configuration/analytics.md
      - Debug Settings: sdk/developer/configuration/debug-settings.md
    - User Interface:
      - sdk/developer/configuration/ui/index.md
      - Theme: sdk/developer/configuration/ui/theme/index.md
      - Color: sdk/developer/configuration/ui/theme/color.md
      - Label: sdk/developer/configuration/ui/theme/label.md
      - Image: sdk/developer/configuration/ui/theme/image.md
      - Button: sdk/developer/configuration/ui/theme/button.md
      - Page Bar: sdk/developer/configuration/ui/theme/page-bar.md
      - Bottom Sheet: sdk/developer/configuration/ui/theme/bottom-sheet.md
      - Activity Indicator: sdk/developer/configuration/ui/theme/activity-indicator.md
      - Selection: sdk/developer/configuration/ui/theme/selection.md
      - Error: sdk/developer/configuration/ui/theme/error.md
      - Product Bar: sdk/developer/configuration/ui/theme/product-bar.md
      - Powered By: sdk/developer/configuration/ui/theme/powered-by.md
    - Features:
      - sdk/developer/configuration/features/index.md
      - Welcome Screen: sdk/developer/configuration/features/welcome-screen.md
      - Onboarding: sdk/developer/configuration/features/onboarding.md
      - Consent: sdk/developer/configuration/features/consent.md
      - Image Picker: sdk/developer/configuration/features/image-picker.md
      - Try On: sdk/developer/configuration/features/try-on.md
      - Share: sdk/developer/configuration/features/share.md
      - Wishlist: sdk/developer/configuration/features/wishlist.md

  - Android:
    - sdk/android/index.md
    - Try-On with UI:
      - Installation: sdk/android/tryon-ui/installation.md
      - Configuration: sdk/android/tryon-ui/configuration.md
      - Default Configuration: sdk/android/tryon-ui/default-configuration.md
    - Try-On:
      - Installation: sdk/android/tryon/installation.md
    - Base:
      - Getting started with Aiuta: sdk/android/base/aiuta-getting-started.md
    - Analytics:
      - Installation: sdk/android/analytics/overview.md
    - Migrations:
      - Migrate to v4: sdk/android/migrations/migrate-v4.md
    - FAQ: sdk/android/faq.md
    - API Reference: https://aiuta-com.github.io/aiuta-android-sdk/

  - iOS:
    - sdk/ios/index.md
    - Installation: sdk/ios/installation.md
    - Configuration: sdk/ios/configuration.md
    - Basic Usage: sdk/ios/basic-usage.md
    - Quick Test: sdk/ios/quick-test.md

  - Flutter:
    - sdk/flutter/index.md
    - Installation: sdk/flutter/installation.md
    - Configuration: sdk/flutter/configuration.md
    - Basic Usage: sdk/flutter/basic-usage.md
    - Migration: 
      - Migrate to v4: sdk/flutter/migration/v4.md

  - Web:
    - sdk/web/index.md
    - Configuration: sdk/web/configuration.md

  - Shopify:
    - shopify/index.md

  - API:
    - api/index.md
    - Getting Started: api/getting-started.md
    - Server-side Auth: api/server-side-auth-component.md
    - Try-On:
      - api/try-on/index.md
      - Workflow: api/try-on/workflow.md
      - Reference: api/try-on/reference.md
    - Flat Lays:
      - api/flat-lays/index.md
      - Workflow: api/flat-lays/workflow.md
      - Reference: api/flat-lays/reference.md

  - Insights:
    - team/index.md
    - Docs:
      - Convention: team/docs/convention.md
      - Local Build: team/docs/local-build.md
      - Swagger UI: team/docs/swagger-ui.md
    - SDK:
      - API Endpoints: team/sdk/api-endpoints.md
      - Subscription Details: team/sdk/subscription-details.md
      - Internal Analytics: team/sdk/analytics.md
      
extra:
  nav:
    divider_after:
      - About
      - Web
    divider_before:
      - Insights
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aiuta-com
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/aiuta-inc
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/aiutacom
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/aiutacom/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AiutaCom
    - icon: aiuta/logo-sq
      link: https://aiuta.com
  aiuta:
    github:
      url: https://github.com
      api: https://api.github.com/repos
      team: aiuta-com
      repos:
        android: aiuta-android-sdk # macro: repo_android(), latest_android()
        ios: aiuta-ios-sdk # macro: repo_ios(), latest_ios()
        flutter: aiuta-flutter-sdk # macro: repo_flutter(), latest_flutter()
        web: aiuta-web-sdk # macro: repo_web(), latest_web()
    api:
      base_url: https://api.aiuta.com
      demo_key: AIUTADEMO
      path:
        try_on: digital-try-on/v1 # macro: api_try_on()
        flat_lays: flat-lays/v1 # macro: api_flat_lays()
        analytics: analytics/v1 # macro: api_analytics()

theme:
  name: 'material'
  custom_dir: overrides
  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - content.code.annotate
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: media/site/favicon.svg
  logo: media/site/logo.svg
  icon:
    logo: aiuta/logo
    annotation: material/information-outline

extra_css:
  - stylesheets/extra.css
  - stylesheets/aiuta.css

plugins:
  - search
  - exclude-search:
      exclude:
        - sdk/templates/*  
        - api/templates/*
        - team/sdk/templates/*
  - minify:
      minify_html: true
  - include-markdown
  - macros

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

validation:
  nav:
    omitted_files: ignore
  links:
    absolute_links: relative_to_docs
    unrecognized_links: warn
    anchors: warn
